# Generated by Django 4.0.4 on 2022-05-02 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gsb_id', models.CharField(max_length=20)),
                ('mate1_id', models.CharField(max_length=20)),
                ('mate2_id', models.CharField(max_length=20)),
                ('mate3_id', models.CharField(max_length=20)),
            ],
        ),
    ]
